// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Xamarin.Interactive.Client.Mac
{
	public partial class StatusToolbarViewProgressIndicator : NSProgressIndicator
	{
		public StatusToolbarViewProgressIndicator (IntPtr handle) : base (handle)
		{
		}
	}
}
